import asyncio, os, sys, json
sys.path.insert(0, "/home/user/promo-bot"); sys.path.insert(0, "/home/user/promo-bot/tests/_sim")
sys.argv=['x']
exec(open('tests/_sim/sim_orders.py').read().split('async def main():')[0])
from app.db.repo import users
async def main():
    await db.init_pool(os.environ["DATABASE_URL"]); await db.run_migrations()
    await db.execute("TRUNCATE fsm_state, events, ledger, topups, order_media, orders RESTART IDENTITY CASCADE")
    await db.execute("DELETE FROM users WHERE tg_id IN (555,556,999)")
    bot = Bot("123456:TESTTOKEN", session=FakeSession(), default=DefaultBotProperties(parse_mode="HTML")); dp = build_dispatcher()
    async def step(l, u, full=False): await dp.feed_update(bot, u); show(l, full)
    U=555; A=999
    for uid in (U, A):
        await dp.feed_update(bot, msg(uid, "/start")); await dp.feed_update(bot, cb(uid, "nav:accept"))
    sent.clear()
    await users.upsert_user(U, "سامر", "samer"); await money_svc.credit(U, Decimal("100"), "topup", note="sim")
    await step("انطلاقة متجر", cb(U, "meta:pkg:bundle"))
    await step("الفرق بين الباقات", cb(U, "meta:diff"))
    await dp.feed_update(bot, cb(U, "meta:pkgs")); await dp.feed_update(bot, cb(U, "meta:pkg:bundle")); sent.clear()
    await dp.feed_update(bot, cb(U, "meta:plat:facebook")); await dp.feed_update(bot, cb(U, "meta:goal:traffic"))
    await dp.feed_update(bot, cb(U, "meta:ctry:SY")); sent.clear()
    await step("رجوع من المحافظات إلى الدولة", cb(U, "meta:back:country"))
    await dp.feed_update(bot, cb(U, "meta:ctry:IQ")); sent.clear()
    await step("رجوع من الجمهور", cb(U, "meta:back:goal"))
    await dp.feed_update(bot, cb(U, "meta:goal:traffic")); await dp.feed_update(bot, cb(U, "meta:ctry:IQ")); await dp.feed_update(bot, cb(U, "meta:aud_done"))
    await dp.feed_update(bot, msg(U, "https://mystore.example.com/offer")); await dp.feed_update(bot, msg(U, "متجر إلكتروني للعطور في بغداد مع توصيل")); sent.clear()
    await step("الملفات (حزمة: النص مضمّن → لا سؤال نص؟)", cb(U, "meta:media_done"))
    if any(n=="EditMessageText" and "نص الإعلان" in (d.get("text") or "") for n,d in sent): pass
    sent.clear()
    st = await dp.fsm.get_context(bot, U, U).get_state(); print("STATE after media_done:", st)
    if st and st.endswith("whatsapp"):
        await dp.feed_update(bot, msg(U, "+9647701234567"))
    else:
        await dp.feed_update(bot, cb(U, "meta:addon:copy:0")); await dp.feed_update(bot, msg(U, "+9647701234567"))
    sent.clear()
    await step("ملخص الحزمة (38$)", cb(U, "meta:wa_ok"), full=True)
    await step("تعديل → يرجع لأول خطوة", cb(U, "meta:edit"))
    await dp.feed_update(bot, cb(U, "meta:plat:instagram")); await dp.feed_update(bot, cb(U, "meta:goal:traffic")); await dp.feed_update(bot, cb(U, "meta:ctry:IQ")); await dp.feed_update(bot, cb(U, "meta:aud_done"))
    await dp.feed_update(bot, msg(U, "https://mystore.example.com/offer")); await dp.feed_update(bot, msg(U, "متجر إلكتروني للعطور في بغداد مع توصيل")); await dp.feed_update(bot, cb(U, "meta:media_done"))
    st = await dp.fsm.get_context(bot, U, U).get_state()
    if not (st and st.endswith("whatsapp")): await dp.feed_update(bot, cb(U, "meta:addon:copy:0"))
    await dp.feed_update(bot, msg(U, "+9647701234567")); sent.clear()
    await step("ملخص بعد التعديل", cb(U, "meta:wa_ok"), full=True)
    await step("تأكيد الحزمة", cb(U, "meta:confirm"))
    o = await db.fetchrow("select * from orders where id=1"); print("ORDER:", o["status"], o["price_usd"], o["cost_usd"], json.loads(o["spec"]).get("pkg"), "addons:", json.loads(o["spec"]).get("addons"), "payload:", json.dumps(json.loads(o["nour_payload"]), ensure_ascii=False)[:200])
    print("balance:", await db.fetchval("select balance_usd from users where tg_id=555"))
    await step("إلغاء داخل المعالج", cb(U, "meta:pkg:growth")); await step("إلغاء", cb(U, "meta:cancel"))
    await step("طلب مسودة ثم إلغاء المسودة", cb(U, "meta:pkg:pro"))
    await dp.feed_update(bot, cb(U, "meta:plat:facebook")); await dp.feed_update(bot, cb(U, "meta:goal:post_promotion")); await dp.feed_update(bot, cb(U, "meta:ctry:JO")); await dp.feed_update(bot, cb(U, "meta:aud_done"))
    await dp.feed_update(bot, msg(U, "https://facebook.com/p/1")); await dp.feed_update(bot, msg(U, "صفحة عقارات في عمّان")); await dp.feed_update(bot, cb(U, "meta:media_done")); await dp.feed_update(bot, cb(U, "meta:addon:copy:0")); await dp.feed_update(bot, msg(U, "+962790000000")); sent.clear()
    await step("ملخص رصيد ناقص (62$ < 65$)", cb(U, "meta:wa_ok"))
    await step("القائمة الرئيسية تظهر المسودة؟", msg(U, "🏠 القائمة"))
    await step("الباقات مع مسودة", cb(U, "nav:meta"))
    await step("إلغاء المسودة", cb(U, "ord:draft_cancel:2"))
    print("orders:", [(r['id'], r['status']) for r in await db.fetch("select id,status from orders order by id")])
    await step("طلباتي", cb(U, "nav:orders"))
    await step("تجديد #1", cb(U, "ord:renew:1"))
    await step("/orders", msg(U, "/orders"))
    await step("مساعدة بهذا الطلب", cb(U, "ord:help:1"))
    await step("أدمن: بطاقة الطلب + ملفات (لا شيء)", cb(A, "adm:ord:1:media"))
    await step("أدمن: sync (DRY)", cb(A, "adm:ord:1:sync"))
    await step("أدمن: مراسلة", cb(A, "adm:ord:1:msg")); await step("أدمن: نص الرسالة", msg(A, "مرحباً، تأكد أنك أدمن على الصفحة"))
    await step("أدمن: إعدادات → المعرّف الاحتياطي", cb(A, "adm:settings")); await step("أدمن: تعديل المعرّف", cb(A, "adm:fallback")); await step("أدمن: حفظ", msg(A, "@Rafat_Support"))
    bal = await db.fetchval("select balance_usd from users where tg_id=555"); ls = await money_svc.ledger_sum(U); print("balance/ledger:", bal, ls)
    await db.close_pool()
asyncio.run(main())
